<table style="width: 100%; height: 100%;">
<tr><td style="height: 20%;">
	<table class="boxNote" style="margin: 20px; margin-left: auto;">
	<tr><td class="boxNote">
		Business Hours:<br />Weekdays: 6:00pm ~ 2:00am<br />Saturday: 5:00pm ~ 2:00am<br />Closed on Sundays
	</td></tr>
	</table>
</td></tr>
<tr><td>
<div class="title" align="center">Contact Information</div>
<table class="boxNote" style="margin: 20px; margin-left: auto; margin-right: auto;">
<tr><td class="boxNote">
	Horst &amp; Hiroshi<br />
	Verde Roppongi 101<br />
	7-16-11 Roppongi, Minato-Ku Tokyo, 106-0032<br />
	Email: <img style="vertical-align: bottom;" src="email.png" /><br />
	Tel: 03-3408-5487<br />
</td></tr>
</table>
</td></tr>
<tr><td style="height: 20%;">
</td></tr>
</table>
